# Data Preprocessing | IBM SkillsBuild Internship

## Import the required libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 nan]
 ['China' 35.0 58000.0]
 ['Thailand ' nan 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 nan]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' nan 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' nan 55000.0]
 ['China' 41.0 nan]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Solving for missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 62562.5]
 ['China' 35.0 58000.0]
 ['Thailand ' 38.5625 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 62562.5]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' 38.5625 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' 38.5625 55000.0]
 ['China' 41.0 62562.5]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


### Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
y = Le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [15]:
print(x_train)

[[0.0 0.0 0.0 1.6583123951777 2.220427630266929 2.3853680018580143]
 [1.0 0.0 0.0 -0.6030226891555271 0.3153483504798985 0.07474012715442147]
 [0.0 0.0 0.0 1.6583123951777 -0.10679989901836391 -0.8147726537679184]
 [0.0 1.0 0.0 -0.6030226891555271 0.14215932504471393 0.07474012715442147]
 [0.0 0.0 1.0 -0.6030226891555271 -1.589730929307132 -0.6463441982086588]
 [1.0 0.0 0.0 -0.6030226891555271 -0.723785802131209 -0.30948728709013956]
 [0.0 1.0 0.0 -0.6030226891555271 -0.10679989901836391
  -1.8253433871234763]
 [0.0 0.0 0.0 1.6583123951777 -0.3774077512608398 0.44844076292652874]
 [0.0 1.0 0.0 -0.6030226891555271 1.5276715285261906 1.4590114962820866]
 [0.0 1.0 0.0 -0.6030226891555271 -1.7629199547423164 -1.1516295648864376]
 [0.0 0.0 0.0 1.6583123951777 -0.5505967766960244 -0.14105883153087995]
 [1.0 0.0 0.0 -0.6030226891555271 -0.20421872582565523
  -0.056844603751250125]
 [0.0 1.0 0.0 -0.6030226891555271 0.8349154267854523 0.8695119018246779]
 [0.0 0.0 1.0 -0.6030226891555271 -0.106